prognostic_run: Ignore pre-existing files in post-process
VulcanClimateModeling/fv3net pull request #1134
Opened 2021-04-06 18:35 UTC by oliverwm1

Prognostic runs (especially segmented ones) upload many duplicate files which wastes time and storage. This PR adds an option to ignore a specified list of files to the post-processing script. The runfile saves a list of existing files in the rundir at start time, which is then used by the post-processing script.

Refactored public API:
- `post_process` function takes an optional `skip` argument which is a list of filenames relative to rundir root

Significant internal changes:
- write list of existing files at start of `sklearn_runfile.py` main

- [ ] Tests added

Resolves #950

2021-04-06 18:37 UTC, oliverwm1 commented on workflows/prognostic_c48_run/runtime/config.py
> +        items.remove("./logs.txt")
This is a bit hacky... not sure how to handle this beyond defining a new command line function which is called in `runfv3` before the `mpirun RUNFILE | tee logs.txt` call.

2021-04-06 20:29 UTC, oliverwm1 commented on workflows/prognostic_c48_run/runtime/config.py
> +        items.remove("./logs.txt")
This point is no longer relevant.

2021-04-07 22:02 UTC, nbren12 requested changes
Small PR, but I think it can be made significantly simpler. See my suggestions below.

2021-04-07 22:02 UTC, nbren12 commented on workflows/post_process_run/fv3post/post_process.py
> +        with open(skip) as f:
If you use `find`, then the output will be one file per line of f
```suggestion
        with open(skip) as f:
            skip = [line.strip() for line in f.readlines()]
```

2021-04-08 19:30 UTC, oliverwm1 commented on workflows/post_process_run/fv3post/post_process.py
This is a change in behavior. For example, now initial conditions would be uploaded even though they are redundant. I'll probably add a `tiles = set(tiles) - set(skip)` also.

2021-04-08 19:31 UTC, oliverwm1 commented on workflows/prognostic_c48_run/runfv3
> +    list_rundir "$rundir" > "$rundir/preexisting_files.yaml"
Okay. Might make it more work to switch `runfv3` to a python script though, which is an ultimate goal I believe.

2021-04-08 19:32 UTC, oliverwm1 commented on workflows/prognostic_c48_run/runfv3
> +    list_rundir "$rundir" > "$rundir/preexisting_files.yaml"
I agree defining a new CLI entrypoint for this seems overkill though.

2021-04-09 16:42 UTC, nbren12 approved these changes

2021-04-09 16:44 UTC, merged